from backend.routes.work import *
from backend.routes.essays import *
from backend.routes.photos import *
from backend.routes.friends import *
from backend.routes.about import *
from backend.routes.contact import *
from backend.routes.music import *
from backend.routes.stack import *
from backend.routes.git_api import *
from backend.routes.readme import *
